batch_size : 2
optim : 'bert'
# Hyper-parameters of Networks:
divide_and_rule: False               # whether use the divide-and-rule strategy
epoch: 20
gpu: 0
lr: 1e-5
not_fine_tuned: False                # do not fine-tune simclr True/False
use_ins_dia: False                  # whether use instructional diagram to strengthen representations or not
weight_decay: 10e-6

dataset:
  batch_size: 2
  data_path: '/data/majie/majie/codehub/2020-opentqa/opentqa/datasets/'
  num_works: 8

pretrained_emb:
  name: en_trf_bertbaseuncased_lg   # choices:en_vectors_web_lg, en_trf_robertabase_lg, en_trf_bertbaseuncased_lg
  size: 768

simclr:
  base_model: 'resnet50'            # choose resnet-xx model
  out_dim: 128
  checkpoints_folder: '/data/majie/majie/codehub/simclr/runs/Oct13_11-08-36_lthpc/checkpoints/'